{
    {
        console.log("\n\n\n\n1---------------------------");
        console.log(Math.LN10);
    }{
        console.log("\n\n\n\n2---------------------------");
        console.log(Math.round(Math.LN10));
    }
}
